[package]
name = "shining-a-light-on-async-internals"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.161"
tokio = { version = "1.41.0", features = ["full"] }

[[bin]]
name = "ffi"
path = "src/bins/ffi/main.rs"

[[bin]]
name = "sm"
path = "src/bins/sm/main.rs"
